# Generated by Django 5.1.2 on 2024-10-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('ids', models.JSONField()),
            ],
        ),
    ]
